turbomachinery: axial_turbine
operation_points:
  fluid_name: air          # Fluid
  p0_in: 12.4e4            # Inlet total pressure
  T0_in: 298.9             # Inlet total temperature
  p_out:  12.4e4/4.64      # Exit static pressure
  alpha_in: 0              # Flow angle at first stator
  omega: 1627              # Rotational speed

simulation_options:
  choking_citerion : evaluate_cascade_critical 
  deviation_model : aungier
  rel_step_fd: 1e-3
  loss_model:
    model: benner
    loss_coefficient: stagnation_pressure
    inlet_displacement_thickness_height_ratio: 0.011

performance_analysis :
  performance_map:
    fluid_name: air
    T0_in: 298.9
    p0_in: 12.4e4
    p_out: 12.4e4/np.linspace(2.0, 6.0, 40)
    omega: 1627
    alpha_in: 0 
  solver_options:
    method: hybr
    tolerance: 1e-8
    max_iterations: 100
    derivative_method: "2-point"
    derivative_abs_step: 1e-6  
    print_convergence: True
    plot_convergence: False
  initial_guess :
    n_samples : 100
    efficiency_tt : (0.7, 0.99)
    efficiency_ke : (0.2, 0.6)
    ma : (0.5, 1.2)


geometry:
  cascade_type : ["stator", "rotor", "stator", "rotor"]
  radius_hub_in : [0.084785, 0.084785, 0.081875, 0.079185]           
  radius_hub_out :  [0.084785, 0.081875, 0.079185, 0.076005]
  radius_tip_in : [0.118415, 0.118415, 0.121325, 0.124015] 
  radius_tip_out : [0.118415, 0.121325, 0.124015, 0.127195]                                                
  pitch: [1.8294e-2, 1.524e-2, 1.484e-2, 1.451e-2]                              
  chord: [2.616e-2, 2.606e-2, 2.182e-2, 2.408e-2]                               
  maximum_thickness: [0.505e-2, 0.447e-2, 0.328e-2, 0.280e-2]                       
  opening: [0.747503242e-2, 0.735223377e-2, 0.803714627e-2, 0.963363217e-2]
  leading_edge_wedge_angle: [50.0, 50.0, 50.0, 50.0]                                                          
  leading_edge_diameter: [2*0.127e-2, 2*0.081e-2, 2*0.097e-2, 2*0.081e-2]                
  trailing_edge_thickness: [0.050e-2, 0.050e-2, 0.050e-2, 0.050e-2]                        
  stagger_angle: [43.03, -31.05, 28.72, -21.75]                                 
  leading_edge_angle: [0.0, 29.6, -26.1, 13.9]                                      
  tip_clearance: [0.0, 0.030e-2,0.0,0.038e-2]                                   
  throat_location_fraction: [5/6, 5/6, 5/6, 5/6]

